version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/src/database/migration.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: todo-api
    build:
      context: ./server
    image: todo-api
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: todo-list
    links:
      - db

  client:
    container_name: todo-client
    build:
      context: ./client
    image: todo-client
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: api
    links:
      - db

volumes:
  db:
    driver: local
