version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/src/database/migration.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    image: vrazn/todo-api
    depends_on:
      - db
    ports:
      - 3001:3001
    links:
      - db

  client:
    image: vrazn/todo-client
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - db

volumes:
  db:
    driver: local
