-- Databases to be used.
SELECT 'CREATE DATABASE "todo-list"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '"todo-list"')\gexec
\c todo-list;

-- Tables to be used.
DROP TABLE IF EXISTS todos;
CREATE TABLE todos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(20) NOT NULL,
  description TEXT,
  is_important BOOLEAN NOT NULL DEFAULT FALSE,
  is_done BOOLEAN NOT NULL DEFAULT FALSE,
  due_date DATE
);

-- Seed values
INSERT INTO todos (title, is_important, is_done, due_date, description) VALUES 
  ('Test 1', TRUE, FALSE, NOW(), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
  ('Test 2', FALSE, FALSE, NULL, NULL), 
  ('Test 3', FALSE, TRUE, NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at commodo odio. Nam ex ante, pellentesque commodo libero vel'),
  ('Test 4', TRUE, FALSE, NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at commodo odio. Nam ex ante, pellentesque commodo libero vel, gravida vestibulum ipsum. Integer condimentum eleifend metus, sed consectetur dolor efficitur quis. Morbi quam nisi, hendrerit at erat at, molestie suscipit lectus.'), 
  ('Test 5', FALSE, FALSE, NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at commodo odio. Nam ex ante, pellentesque commodo libero vel, gravida vestibulum ipsum. Integer condimentum eleifend metus, sed consectetur dolor efficitur quis. Morbi quam nisi, hendrerit at erat at, molestie suscipit lectus.'), 
  ('Test 6', FALSE, FALSE, NOW(), NULL), 
  ('Test 7', FALSE, FALSE, NOW(), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
  ('Test 8', FALSE, TRUE, NULL, NULL),
  ('Test 9', TRUE, TRUE, NOW(), NULL),
  ('Test 10', FALSE, TRUE, NOW(), NULL),
  ('Test 11', FALSE, TRUE, NOW(), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at commodo odio.'),
  ('Test 12', TRUE, FALSE, NULL, NULL), 
  ('Test 13', TRUE, FALSE, NOW(), NULL), 
  ('Test 14', TRUE, TRUE, NULL, NULL),
  ('Test 15', TRUE, TRUE, NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at commodo odio. Nam ex ante, pellentesque commodo libero vel'),
  ('Test 16', TRUE, TRUE, NOW(), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at commodo odio.');
