-- Databases to be used.
SELECT 'CREATE DATABASE "todo-ist"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '"todo-ist"')\gexec
\c todo-ist;

-- Tables to be used.
DROP TABLE IF EXISTS todos;
CREATE TABLE todos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(20) NOT NULL,
  is_done BOOLEAN NOT NULL DEFAULT FALSE
);

-- Seed values
INSERT INTO todos (title) VALUES ('Test 1'), ('Test 2'), ('Test 3');
